name: Producer CPP SDK CI

on:
  push:
    branches:
      - develop
      - master
      - OpenSSL3-build
  pull_request:
    branches:
      - develop
      - master

jobs:
  ubuntu-22:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    env:
      CC: clang
      CXX: clang++
      AWS_KVS_LOG_LEVEL: 2
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Fix 22.04 virt env
        # The 22.04 virtual environment includes libunwind-14-dev, which conflicts with libunwind-dev
        run: |
          sudo apt-get remove libunwind-14 -y
          sudo apt-get install libunwind-dev -y
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y libssl-dev libcurl4-openssl-dev liblog4cplus-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base-apps gstreamer1.0-plugins-bad gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-tools
      - name: Build repository
        run: |
          mkdir build && cd build
          cmake .. -DBUILD_TEST=FALSE -DBUILD_GSTREAMER_PLUGIN=TRUE -DBUILD_JNI=FALSE
          make
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: jammy
          path: |
            ./build/dependency/libkvscproducer/kvscproducer-src/libcproducer.so
            ./build/libKinesisVideoProducer.so
            ./build/libgstkvssink.so

